### PR TITLE
Bump build version to build against latest Eigen

### PR DESCRIPTION
**Pull request by traversaro**
See https://github.com/conda-forge/ceres-solver-feedstock/issues/19#issuecomment-922063835 for the rationale.

Checklist
* [x] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [x] Bumped the build number (if the version is unchanged)
* [ ] Reset the build number to `0` (if the version changed)
* [x] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [x] Ensured the license file is being packaged.

### CODE REVIEW

**Comment by traversaro** [comment]
@conda-forge-admin, please rerender

**Comment by Tobias-Fischer** [comment]
Thanks @traversaro!

**Comment by Tobias-Fischer** [comment]
I suggest to go straight for #23 instead?

**Comment by traversaro** [comment]
> I suggest to go straight for #23 instead?

Good idea!

**Comment by traversaro** [comment]
Superseded by https://github.com/conda-forge/ceres-solver-feedstock/pull/23 .

**Comment by jschueller** [comment]
I already bumped it in https://github.com/conda-forge/ceres-solver-feedstock/pull/21

**Comment by Tobias-Fischer** [comment]
Ahh .. in cartographer we have to use v1 of ceres-solver. I opened a PR for that branch in #24

**Pull request closed without merging**
